name: Publish

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Deploy:
    runs-on: Linux RedHat AS5
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '1.20.1'

    - name: Build
      run: hugo -D

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server:  http://host7201118.xincache1.cn/www/IMG
        ftp-username: host7201118
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/